# Generated by Django 6.0.6 on 2026-07-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_id_remove_member_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
